# Generated by Django 3.2.9 on 2021-11-26 19:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled Form', max_length=128)),
                ('description', models.TextField()),
                ('slug', models.SlugField(max_length=256, unique=True)),
                ('form_template', models.CharField(choices=[('blank', 'BLANK'), ('cv', 'CV'), ('quiz', 'QUIZ'), ('registration', 'REGISTRATION')], default='blank', max_length=16)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('owner_is_anonymous', models.BooleanField(default=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='accounts.business')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_body', models.CharField(max_length=256)),
                ('related_image', models.ImageField(blank=True, null=True, upload_to='media/question_related_images')),
                ('answer_type', models.CharField(choices=[('long', 'Long'), ('short', 'Short'), ('multi', 'MultipleChoice'), ('email', 'Email'), ('phone-no', 'Phone No.'), ('number', 'Number'), ('file', 'File')], max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='form_builder.form')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_email', models.EmailField(max_length=254, null=True)),
                ('related_form', models.ForeignKey(on_delete=models.SET('deleted-form'), related_name='responses', to='form_builder.form')),
            ],
        ),
        migrations.CreateModel(
            name='ShortAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_field', models.CharField(max_length=256, null=True)),
                ('related_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='short_answers', to='form_builder.question')),
                ('related_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='short_answers', to='form_builder.response')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneNumberFieldAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_field', models.CharField(max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('related_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phonenum_answers', to='form_builder.question')),
                ('related_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phonenum_answers', to='form_builder.response')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NumberFieldAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_field', models.BigIntegerField(null=True)),
                ('related_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='number_answers', to='form_builder.question')),
                ('related_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='number_answers', to='form_builder.response')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MultipleChoiceAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_answers', to='form_builder.choices')),
                ('related_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multichoice_answers', to='form_builder.question')),
                ('related_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multichoice_answers', to='form_builder.response')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LongAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_field', models.TextField(null=True)),
                ('related_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='long_answers', to='form_builder.question')),
                ('related_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='long_answers', to='form_builder.response')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FileFieldAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_field', models.FileField(upload_to='media/file_field_question_answers')),
                ('related_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_answers', to='form_builder.question')),
                ('related_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_answers', to='form_builder.response')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmailFieldAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_field', models.EmailField(max_length=254, null=True)),
                ('related_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_answers', to='form_builder.question')),
                ('related_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_answers', to='form_builder.response')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='choices',
            name='related_question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='form_builder.question'),
        ),
    ]
